# Generated by Django 3.2.5 on 2021-07-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicionindicador',
            options={'verbose_name': 'Medicion de Indicador'},
        ),
        migrations.AddField(
            model_name='medicionindicador',
            name='area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='visor.area'),
            preserve_default=False,
        ),
    ]
