# Generated by Django 3.2.5 on 2021-08-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0002_auto_20210728_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
    ]
